# Generated by Django 2.0.2 on 2018-03-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_data',
            new_name='invoice_date',
        ),
    ]
