# Generated by Django 2.0.2 on 2018-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('due_receipt', 'Due of Receipt'), ('due_end_next_month', 'Due End of Next Month'), ('due_end_month', 'Due End of Month')], default='due_receipt', max_length=20),
        ),
    ]
