# Generated by Django 2.0.2 on 2018-03-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180302_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Draft', 'Draft')], max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('Due of Receipt', 'Due of Receipt'), ('Due End of Next Month', 'Due End of Next Month'), ('Due End of Month', 'Due End of Month')], max_length=16),
        ),
    ]
