# Generated by Django 2.0.2 on 2018-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20180320_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
