# Generated by Django 2.0.2 on 2018-03-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Sent', 'Sent'), ('Draft', 'Draft')], default='Sent', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='terms',
            field=models.CharField(choices=[('Due of Receipt', 'Due of Receipt'), ('Due End of Next Month', 'Due End of Next Month'), ('Due End of Month', 'Due End of Month')], default='Due of Receipt', max_length=16),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
