# Generated by Django 2.0.2 on 2018-03-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('billing_address', models.CharField(max_length=255)),
            ],
        ),
    ]
